
/* SPDX-License-Identifier: BSD-2-Clause */
/* AUTOGENERATED CODE DO NOT MODIFY */

#ifndef INCLUDE_TSS2_TSS2_MU_YAML_H_
#define INCLUDE_TSS2_TSS2_MU_YAML_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>

#include "tss2_tpm2_types.h"

TSS2_RC
Tss2_MU_YAML_TPM2B_ATTEST_Marshal(
    TPM2B_ATTEST const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_ATTEST_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_ATTEST     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_AUTH_Marshal(
    TPM2B_AUTH const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_AUTH_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_AUTH     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_DATA_Marshal(
    TPM2B_CONTEXT_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_CONTEXT_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_SENSITIVE_Marshal(
    TPM2B_CONTEXT_SENSITIVE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_SENSITIVE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_CONTEXT_SENSITIVE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_CREATION_DATA_Marshal(
    TPM2B_CREATION_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_CREATION_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_CREATION_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_DATA_Marshal(
    TPM2B_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_DERIVE_Marshal(
    TPM2B_DERIVE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_DERIVE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_DERIVE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_DIGEST_Marshal(
    TPM2B_DIGEST const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_DIGEST_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_DIGEST     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_PARAMETER_Marshal(
    TPM2B_ECC_PARAMETER const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_PARAMETER_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_ECC_PARAMETER     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_POINT_Marshal(
    TPM2B_ECC_POINT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_POINT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_ECC_POINT     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ENCRYPTED_SECRET_Marshal(
    TPM2B_ENCRYPTED_SECRET const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_ENCRYPTED_SECRET_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_ENCRYPTED_SECRET     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_EVENT_Marshal(
    TPM2B_EVENT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_EVENT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_EVENT     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ID_OBJECT_Marshal(
    TPM2B_ID_OBJECT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_ID_OBJECT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_ID_OBJECT     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_IV_Marshal(
    TPM2B_IV const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_IV_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_IV     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_LABEL_Marshal(
    TPM2B_LABEL const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_LABEL_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_LABEL     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_BUFFER_Marshal(
    TPM2B_MAX_BUFFER const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_BUFFER_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_MAX_BUFFER     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_CAP_BUFFER_Marshal(
    TPM2B_MAX_CAP_BUFFER const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_CAP_BUFFER_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_MAX_CAP_BUFFER     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_NV_BUFFER_Marshal(
    TPM2B_MAX_NV_BUFFER const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_NV_BUFFER_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_MAX_NV_BUFFER     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_NAME_Marshal(
    TPM2B_NAME const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_NAME_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_NAME     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_NONCE_Marshal(
    TPM2B_NONCE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_NONCE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_NONCE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_NV_PUBLIC_Marshal(
    TPM2B_NV_PUBLIC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_NV_PUBLIC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_NV_PUBLIC     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_OPERAND_Marshal(
    TPM2B_OPERAND const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_OPERAND_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_OPERAND     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_Marshal(
    TPM2B_PRIVATE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_PRIVATE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_KEY_RSA_Marshal(
    TPM2B_PRIVATE_KEY_RSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_KEY_RSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_PRIVATE_KEY_RSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_VENDOR_SPECIFIC_Marshal(
    TPM2B_PRIVATE_VENDOR_SPECIFIC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_VENDOR_SPECIFIC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_PRIVATE_VENDOR_SPECIFIC     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_Marshal(
    TPM2B_PUBLIC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_PUBLIC     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_KEY_RSA_Marshal(
    TPM2B_PUBLIC_KEY_RSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_KEY_RSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_PUBLIC_KEY_RSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_Marshal(
    TPM2B_SENSITIVE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_SENSITIVE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_CREATE_Marshal(
    TPM2B_SENSITIVE_CREATE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_CREATE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_SENSITIVE_CREATE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_DATA_Marshal(
    TPM2B_SENSITIVE_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_SENSITIVE_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SYM_KEY_Marshal(
    TPM2B_SYM_KEY const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_SYM_KEY_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_SYM_KEY     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_TEMPLATE_Marshal(
    TPM2B_TEMPLATE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_TEMPLATE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_TEMPLATE     *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_TIMEOUT_Marshal(
    TPM2B_TIMEOUT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPM2B_TIMEOUT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPM2B_TIMEOUT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ACT_DATA_Marshal(
    TPMS_ACT_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ACT_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ACT_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_AC_OUTPUT_Marshal(
    TPMS_AC_OUTPUT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_AC_OUTPUT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_AC_OUTPUT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ALGORITHM_DETAIL_ECC_Marshal(
    TPMS_ALGORITHM_DETAIL_ECC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ALGORITHM_DETAIL_ECC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ALGORITHM_DETAIL_ECC     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ALG_PROPERTY_Marshal(
    TPMS_ALG_PROPERTY const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ALG_PROPERTY_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ALG_PROPERTY     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ASYM_PARMS_Marshal(
    TPMS_ASYM_PARMS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ASYM_PARMS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ASYM_PARMS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ATTEST_Marshal(
    TPMS_ATTEST const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ATTEST_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ATTEST     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_AUTH_COMMAND_Marshal(
    TPMS_AUTH_COMMAND const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_AUTH_COMMAND_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_AUTH_COMMAND     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_AUTH_RESPONSE_Marshal(
    TPMS_AUTH_RESPONSE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_AUTH_RESPONSE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_AUTH_RESPONSE     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CAPABILITY_DATA_Marshal(
    TPMS_CAPABILITY_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CAPABILITY_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CAPABILITY_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CERTIFY_INFO_Marshal(
    TPMS_CERTIFY_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CERTIFY_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CERTIFY_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CLOCK_INFO_Marshal(
    TPMS_CLOCK_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CLOCK_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CLOCK_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_COMMAND_AUDIT_INFO_Marshal(
    TPMS_COMMAND_AUDIT_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_COMMAND_AUDIT_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_COMMAND_AUDIT_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CONTEXT_Marshal(
    TPMS_CONTEXT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CONTEXT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CONTEXT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CONTEXT_DATA_Marshal(
    TPMS_CONTEXT_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CONTEXT_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CONTEXT_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CREATION_DATA_Marshal(
    TPMS_CREATION_DATA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CREATION_DATA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CREATION_DATA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_CREATION_INFO_Marshal(
    TPMS_CREATION_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_CREATION_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_CREATION_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_DERIVE_Marshal(
    TPMS_DERIVE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_DERIVE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_DERIVE     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ECC_PARMS_Marshal(
    TPMS_ECC_PARMS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ECC_PARMS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ECC_PARMS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ECC_POINT_Marshal(
    TPMS_ECC_POINT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ECC_POINT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ECC_POINT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_EMPTY_Marshal(
    TPMS_EMPTY const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_EMPTY_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_EMPTY     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ENC_SCHEME_OAEP_Marshal(
    TPMS_ENC_SCHEME_OAEP const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ENC_SCHEME_OAEP_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ENC_SCHEME_OAEP     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ENC_SCHEME_RSAES_Marshal(
    TPMS_ENC_SCHEME_RSAES const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ENC_SCHEME_RSAES_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ENC_SCHEME_RSAES     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_ID_OBJECT_Marshal(
    TPMS_ID_OBJECT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_ID_OBJECT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_ID_OBJECT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_KEYEDHASH_PARMS_Marshal(
    TPMS_KEYEDHASH_PARMS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_KEYEDHASH_PARMS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_KEYEDHASH_PARMS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_KEY_SCHEME_ECDH_Marshal(
    TPMS_KEY_SCHEME_ECDH const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_KEY_SCHEME_ECDH_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_KEY_SCHEME_ECDH     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_KEY_SCHEME_ECMQV_Marshal(
    TPMS_KEY_SCHEME_ECMQV const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_KEY_SCHEME_ECMQV_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_KEY_SCHEME_ECMQV     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_CERTIFY_INFO_Marshal(
    TPMS_NV_CERTIFY_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_CERTIFY_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_NV_CERTIFY_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_DIGEST_CERTIFY_INFO_Marshal(
    TPMS_NV_DIGEST_CERTIFY_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_DIGEST_CERTIFY_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_NV_DIGEST_CERTIFY_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_PIN_COUNTER_PARAMETERS_Marshal(
    TPMS_NV_PIN_COUNTER_PARAMETERS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_PIN_COUNTER_PARAMETERS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_NV_PIN_COUNTER_PARAMETERS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_PUBLIC_Marshal(
    TPMS_NV_PUBLIC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_NV_PUBLIC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_NV_PUBLIC     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_PCR_SELECT_Marshal(
    TPMS_PCR_SELECT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_PCR_SELECT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_PCR_SELECT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_PCR_SELECTION_Marshal(
    TPMS_PCR_SELECTION const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_PCR_SELECTION_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_PCR_SELECTION     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_QUOTE_INFO_Marshal(
    TPMS_QUOTE_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_QUOTE_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_QUOTE_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_RSA_PARMS_Marshal(
    TPMS_RSA_PARMS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_RSA_PARMS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_RSA_PARMS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_ECDAA_Marshal(
    TPMS_SCHEME_ECDAA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_ECDAA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_ECDAA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_HASH_Marshal(
    TPMS_SCHEME_HASH const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_HASH_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_HASH     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_HMAC_Marshal(
    TPMS_SCHEME_HMAC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_HMAC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_HMAC     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF1_SP800_108_Marshal(
    TPMS_SCHEME_KDF1_SP800_108 const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF1_SP800_108_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_KDF1_SP800_108     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF1_SP800_56A_Marshal(
    TPMS_SCHEME_KDF1_SP800_56A const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF1_SP800_56A_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_KDF1_SP800_56A     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF2_Marshal(
    TPMS_SCHEME_KDF2 const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_KDF2_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_KDF2     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_MGF1_Marshal(
    TPMS_SCHEME_MGF1 const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_MGF1_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_MGF1     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_XOR_Marshal(
    TPMS_SCHEME_XOR const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SCHEME_XOR_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SCHEME_XOR     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SENSITIVE_CREATE_Marshal(
    TPMS_SENSITIVE_CREATE const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SENSITIVE_CREATE_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SENSITIVE_CREATE     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SESSION_AUDIT_INFO_Marshal(
    TPMS_SESSION_AUDIT_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SESSION_AUDIT_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SESSION_AUDIT_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECC_Marshal(
    TPMS_SIGNATURE_ECC const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECC_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_ECC     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECDAA_Marshal(
    TPMS_SIGNATURE_ECDAA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECDAA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_ECDAA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECDSA_Marshal(
    TPMS_SIGNATURE_ECDSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECDSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_ECDSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECSCHNORR_Marshal(
    TPMS_SIGNATURE_ECSCHNORR const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_ECSCHNORR_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_ECSCHNORR     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSA_Marshal(
    TPMS_SIGNATURE_RSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_RSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSAPSS_Marshal(
    TPMS_SIGNATURE_RSAPSS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSAPSS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_RSAPSS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSASSA_Marshal(
    TPMS_SIGNATURE_RSASSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_RSASSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_RSASSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_SM2_Marshal(
    TPMS_SIGNATURE_SM2 const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIGNATURE_SM2_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIGNATURE_SM2     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECDAA_Marshal(
    TPMS_SIG_SCHEME_ECDAA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECDAA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_ECDAA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECDSA_Marshal(
    TPMS_SIG_SCHEME_ECDSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECDSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_ECDSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECSCHNORR_Marshal(
    TPMS_SIG_SCHEME_ECSCHNORR const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_ECSCHNORR_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_ECSCHNORR     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_RSAPSS_Marshal(
    TPMS_SIG_SCHEME_RSAPSS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_RSAPSS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_RSAPSS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_RSASSA_Marshal(
    TPMS_SIG_SCHEME_RSASSA const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_RSASSA_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_RSASSA     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_SM2_Marshal(
    TPMS_SIG_SCHEME_SM2 const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SIG_SCHEME_SM2_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SIG_SCHEME_SM2     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_SYMCIPHER_PARMS_Marshal(
    TPMS_SYMCIPHER_PARMS const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_SYMCIPHER_PARMS_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_SYMCIPHER_PARMS     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_PCR_SELECT_Marshal(
    TPMS_TAGGED_PCR_SELECT const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_PCR_SELECT_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_TAGGED_PCR_SELECT     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_POLICY_Marshal(
    TPMS_TAGGED_POLICY const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_POLICY_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_TAGGED_POLICY     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_PROPERTY_Marshal(
    TPMS_TAGGED_PROPERTY const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_TAGGED_PROPERTY_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_TAGGED_PROPERTY     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_TIME_ATTEST_INFO_Marshal(
    TPMS_TIME_ATTEST_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_TIME_ATTEST_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_TIME_ATTEST_INFO     *dest);

TSS2_RC
Tss2_MU_YAML_TPMS_TIME_INFO_Marshal(
    TPMS_TIME_INFO const *src,
    char        **yaml);

TSS2_RC
Tss2_MU_YAML_TPMS_TIME_INFO_Unmarshal(
    const char *yaml,
    size_t      yaml_len,
    TPMS_TIME_INFO     *dest);

#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_TSS2_TSS2_MU_YAML_H_ */
