/* SPDX-License-Identifier: BSD-2-Clause */

#ifndef INCLUDE_TSS2_TSS2_MU_YAML_H_
#define INCLUDE_TSS2_TSS2_MU_YAML_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "tss2_tpm2_types.h"

/* AUTOGENERATED ASSISTED CODE using yaml_mu_gen.py tpm2b_protos. modify with care */

TSS2_RC
Tss2_MU_YAML_TPM2B_ATTEST_Marshal(
    TPM2B_ATTEST const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_ATTEST_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_ATTEST   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_AUTH_Marshal(
    TPM2B_AUTH const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_AUTH_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_AUTH   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_DATA_Marshal(
    TPM2B_CONTEXT_DATA const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_DATA_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_CONTEXT_DATA   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_SENSITIVE_Marshal(
    TPM2B_CONTEXT_SENSITIVE const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_CONTEXT_SENSITIVE_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_CONTEXT_SENSITIVE   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_DATA_Marshal(
    TPM2B_DATA const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_DATA_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_DATA   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_DIGEST_Marshal(
    TPM2B_DIGEST const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_DIGEST_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_DIGEST   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_PARAMETER_Marshal(
    TPM2B_ECC_PARAMETER const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_ECC_PARAMETER_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_ECC_PARAMETER   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ENCRYPTED_SECRET_Marshal(
    TPM2B_ENCRYPTED_SECRET const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_ENCRYPTED_SECRET_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_ENCRYPTED_SECRET   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_EVENT_Marshal(
    TPM2B_EVENT const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_EVENT_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_EVENT   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_ID_OBJECT_Marshal(
    TPM2B_ID_OBJECT const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_ID_OBJECT_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_ID_OBJECT   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_IV_Marshal(
    TPM2B_IV const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_IV_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_IV   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_BUFFER_Marshal(
    TPM2B_MAX_BUFFER const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_BUFFER_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_MAX_BUFFER   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_NV_BUFFER_Marshal(
    TPM2B_MAX_NV_BUFFER const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_MAX_NV_BUFFER_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_MAX_NV_BUFFER   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_NAME_Marshal(
    TPM2B_NAME const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_NAME_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_NAME   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_NONCE_Marshal(
    TPM2B_NONCE const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_NONCE_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_NONCE   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_OPERAND_Marshal(
    TPM2B_OPERAND const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_OPERAND_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_OPERAND   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_Marshal(
    TPM2B_PRIVATE const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_PRIVATE   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_KEY_RSA_Marshal(
    TPM2B_PRIVATE_KEY_RSA const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_KEY_RSA_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_PRIVATE_KEY_RSA   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_VENDOR_SPECIFIC_Marshal(
    TPM2B_PRIVATE_VENDOR_SPECIFIC const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_PRIVATE_VENDOR_SPECIFIC_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_PRIVATE_VENDOR_SPECIFIC   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_KEY_RSA_Marshal(
    TPM2B_PUBLIC_KEY_RSA const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_PUBLIC_KEY_RSA_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_PUBLIC_KEY_RSA   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_DATA_Marshal(
    TPM2B_SENSITIVE_DATA const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_SENSITIVE_DATA_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_SENSITIVE_DATA   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_SYM_KEY_Marshal(
    TPM2B_SYM_KEY const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_SYM_KEY_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_SYM_KEY   *dest);

TSS2_RC
Tss2_MU_YAML_TPM2B_TEMPLATE_Marshal(
    TPM2B_TEMPLATE const *src,
    char            **output);

TSS2_RC
Tss2_MU_YAML_TPM2B_TEMPLATE_Unmarshal(
    char const      buffer[],
    size_t          buffer_size,
    TPM2B_TEMPLATE   *dest);
#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_TSS2_TSS2_MU_YAML_H_ */
