/* SPDX-License-Identifier: BSD-2-Clause */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <stdlib.h>

#include <setjmp.h>
#include <cmocka.h>

#include "tss2_mu_yaml.h"

#define LOGMODULE tests
#include "util/log.h"
#include "util/aux_util.h"

/* Test for valid YAML */
#define TEST_COMMON_GOOD(type, field, str_expected, expected) \
    do { \
        char *yaml = NULL; \
        TSS2_RC rc = Tss2_MU_YAML_##type##_Marshal(&src, &yaml); \
        assert_int_equal(rc, TSS2_RC_SUCCESS); \
        assert_string_equal(yaml, #field": "str_expected"\n"); \
        \
        type dest = { 0 }; \
        rc =Tss2_MU_YAML_##type##_Unmarshal( \
                yaml, \
                0, \
                &dest); \
        assert_int_equal(rc, TSS2_RC_SUCCESS); \
        assert_int_equal(expected.size, dest.size); \
        assert_memory_equal(expected.field, dest.field, dest.size); \
    } while (0)

/* test for "zero length" inputs, like "", "{}\n", etc */
#define TEST_COMMON_ZERO(type, field) \
    do { \
        char *yaml = (char *)0xbadcafe; \
        static const type src = { 0 }; \
        TSS2_RC rc = Tss2_MU_YAML_##type##_Marshal(&src, &yaml); \
        assert_int_equal(rc, TSS2_RC_SUCCESS); \
        assert_null(yaml); \
        \
        static const type golden; \
        type dest = { 0 }; \
        \
        rc =Tss2_MU_YAML_##type##_Unmarshal( \
                "", \
                0, \
                &dest); \
        assert_int_equal(rc, TSS2_MU_RC_BAD_VALUE); \
        assert_memory_equal(&dest, &golden, sizeof(golden)); \
        \
        rc =Tss2_MU_YAML_##type##_Unmarshal( \
                "notfound: badcafedeadbeefbadccode\n", \
                0, \
                &dest); \
        assert_int_equal(rc, TSS2_MU_RC_BAD_VALUE); \
        assert_memory_equal(&dest, &golden, sizeof(golden)); \
        \
        rc =Tss2_MU_YAML_##type##_Unmarshal( \
                "{}\n", /* empty mapping */ \
                0, \
                &dest); \
        assert_int_equal(rc, TSS2_MU_RC_BAD_VALUE); \
        assert_memory_equal(&dest, &golden, sizeof(golden)); \
    } while(0)

#define TEST_COMMON_NULL(type, field) \
        do { \
            char *yaml = NULL; \
            type data = { 0 }; \
            TSS2_RC rc = Tss2_MU_YAML_##type##_Marshal(NULL, &yaml); \
            assert_int_equal(rc, TSS2_MU_RC_BAD_REFERENCE); \
            \
            rc = Tss2_MU_YAML_##type##_Marshal(&data, NULL); \
            assert_int_equal(rc, TSS2_MU_RC_BAD_REFERENCE); \
            \
            rc =Tss2_MU_YAML_##type##_Unmarshal( \
                    NULL, \
                    0, \
                    &data); \
            assert_int_equal(rc, TSS2_MU_RC_BAD_REFERENCE); \
            \
            rc =Tss2_MU_YAML_##type##_Unmarshal( \
                    "", \
                    0, \
                    NULL); \
            assert_int_equal(rc, TSS2_MU_RC_BAD_REFERENCE); \
        } while(0)

/* AUTOGENERATED ASSISTED CODE using yaml_mu_gen.py tpm2b_tests. modify with care */

void
test_TPM2B_ATTEST_good(void **state)
{
    UNUSED(state);

    static const TPM2B_ATTEST src = {
        .size = 16,
        .attestationData = {
            0xff, 0xd8, 0xaf, 0x32, 0x82, 0x7c, 0xc1, 0x68, 0x14, 0x9f, 0xe7, 0x2e, 0xae, 0x20,
            0x18, 0x95
        }
    };

    TEST_COMMON_GOOD(TPM2B_ATTEST, attestationData,
        "ffd8af32827cc168149fe72eae201895",
        src);
}

void
test_TPM2B_ATTEST_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_ATTEST, attestationData);
}

void
test_TPM2B_ATTEST_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_ATTEST, attestationData);
}

void
test_TPM2B_AUTH_good(void **state)
{
    UNUSED(state);

    static const TPM2B_AUTH src = {
        .size = 16,
        .buffer = {
            0x51, 0xae, 0x00, 0x04, 0x7f, 0x29, 0x58, 0xb0, 0xc7, 0xe7, 0x3d, 0x13, 0xa8, 0xe0,
            0xe2, 0xea
        }
    };

    TEST_COMMON_GOOD(TPM2B_AUTH, buffer,
        "51ae00047f2958b0c7e73d13a8e0e2ea",
        src);
}

void
test_TPM2B_AUTH_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_AUTH, buffer);
}

void
test_TPM2B_AUTH_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_AUTH, buffer);
}

void
test_TPM2B_CONTEXT_DATA_good(void **state)
{
    UNUSED(state);

    static const TPM2B_CONTEXT_DATA src = {
        .size = 16,
        .buffer = {
            0xd2, 0x48, 0x0c, 0x10, 0x85, 0x0f, 0x23, 0x3f, 0x3a, 0x82, 0x87, 0x61, 0xea, 0x4b,
            0x6d, 0xb2
        }
    };

    TEST_COMMON_GOOD(TPM2B_CONTEXT_DATA, buffer,
        "d2480c10850f233f3a828761ea4b6db2",
        src);
}

void
test_TPM2B_CONTEXT_DATA_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_CONTEXT_DATA, buffer);
}

void
test_TPM2B_CONTEXT_DATA_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_CONTEXT_DATA, buffer);
}

void
test_TPM2B_CONTEXT_SENSITIVE_good(void **state)
{
    UNUSED(state);

    static const TPM2B_CONTEXT_SENSITIVE src = {
        .size = 16,
        .buffer = {
            0xf8, 0xe2, 0x44, 0x55, 0x97, 0xb8, 0x69, 0xc6, 0x1e, 0x1b, 0xc7, 0x8f, 0xed, 0x2f,
            0xbd, 0x22
        }
    };

    TEST_COMMON_GOOD(TPM2B_CONTEXT_SENSITIVE, buffer,
        "f8e2445597b869c61e1bc78fed2fbd22",
        src);
}

void
test_TPM2B_CONTEXT_SENSITIVE_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_CONTEXT_SENSITIVE, buffer);
}

void
test_TPM2B_CONTEXT_SENSITIVE_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_CONTEXT_SENSITIVE, buffer);
}

void
test_TPM2B_DATA_good(void **state)
{
    UNUSED(state);

    static const TPM2B_DATA src = {
        .size = 16,
        .buffer = {
            0xdf, 0xea, 0x34, 0xe4, 0xed, 0xa5, 0x01, 0xae, 0x0a, 0xca, 0x24, 0xe0, 0x96, 0x68,
            0xc9, 0xe8
        }
    };

    TEST_COMMON_GOOD(TPM2B_DATA, buffer,
        "dfea34e4eda501ae0aca24e09668c9e8",
        src);
}

void
test_TPM2B_DATA_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_DATA, buffer);
}

void
test_TPM2B_DATA_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_DATA, buffer);
}

void
test_TPM2B_DIGEST_good(void **state)
{
    UNUSED(state);

    static const TPM2B_DIGEST src = {
        .size = 16,
        .buffer = {
            0x8e, 0x32, 0xc6, 0x51, 0xa0, 0xba, 0xf5, 0x7e, 0x0d, 0xf5, 0x70, 0x76, 0xfc, 0x47,
            0x3e, 0xf4
        }
    };

    TEST_COMMON_GOOD(TPM2B_DIGEST, buffer,
        "8e32c651a0baf57e0df57076fc473ef4",
        src);
}

void
test_TPM2B_DIGEST_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_DIGEST, buffer);
}

void
test_TPM2B_DIGEST_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_DIGEST, buffer);
}

void
test_TPM2B_ECC_PARAMETER_good(void **state)
{
    UNUSED(state);

    static const TPM2B_ECC_PARAMETER src = {
        .size = 16,
        .buffer = {
            0x2e, 0xd3, 0x81, 0xff, 0x73, 0xd5, 0xa3, 0x04, 0x40, 0xec, 0x3d, 0x80, 0x4e, 0x09,
            0xde, 0x85
        }
    };

    TEST_COMMON_GOOD(TPM2B_ECC_PARAMETER, buffer,
        "2ed381ff73d5a30440ec3d804e09de85",
        src);
}

void
test_TPM2B_ECC_PARAMETER_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_ECC_PARAMETER, buffer);
}

void
test_TPM2B_ECC_PARAMETER_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_ECC_PARAMETER, buffer);
}

void
test_TPM2B_ENCRYPTED_SECRET_good(void **state)
{
    UNUSED(state);

    static const TPM2B_ENCRYPTED_SECRET src = {
        .size = 16,
        .secret = {
            0x41, 0x9b, 0xc7, 0xd5, 0xdb, 0x85, 0x74, 0x8e, 0x7a, 0x03, 0x8b, 0xf0, 0xe6, 0xab,
            0xe6, 0x7d
        }
    };

    TEST_COMMON_GOOD(TPM2B_ENCRYPTED_SECRET, secret,
        "419bc7d5db85748e7a038bf0e6abe67d",
        src);
}

void
test_TPM2B_ENCRYPTED_SECRET_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_ENCRYPTED_SECRET, secret);
}

void
test_TPM2B_ENCRYPTED_SECRET_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_ENCRYPTED_SECRET, secret);
}

void
test_TPM2B_EVENT_good(void **state)
{
    UNUSED(state);

    static const TPM2B_EVENT src = {
        .size = 16,
        .buffer = {
            0x97, 0x05, 0x2a, 0x64, 0x1b, 0x4d, 0x6b, 0x5e, 0x64, 0x88, 0x9b, 0x2d, 0x92, 0xa3,
            0x80, 0x16
        }
    };

    TEST_COMMON_GOOD(TPM2B_EVENT, buffer,
        "97052a641b4d6b5e64889b2d92a38016",
        src);
}

void
test_TPM2B_EVENT_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_EVENT, buffer);
}

void
test_TPM2B_EVENT_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_EVENT, buffer);
}

void
test_TPM2B_ID_OBJECT_good(void **state)
{
    UNUSED(state);

    static const TPM2B_ID_OBJECT src = {
        .size = 16,
        .credential = {
            0x0e, 0xaf, 0x55, 0xde, 0xca, 0x7f, 0x11, 0xdf, 0x30, 0x15, 0x6a, 0xfe, 0x7e, 0xa9,
            0xce, 0xad
        }
    };

    TEST_COMMON_GOOD(TPM2B_ID_OBJECT, credential,
        "0eaf55deca7f11df30156afe7ea9cead",
        src);
}

void
test_TPM2B_ID_OBJECT_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_ID_OBJECT, credential);
}

void
test_TPM2B_ID_OBJECT_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_ID_OBJECT, credential);
}

void
test_TPM2B_IV_good(void **state)
{
    UNUSED(state);

    static const TPM2B_IV src = {
        .size = 16,
        .buffer = {
            0xb7, 0x62, 0xd8, 0xcd, 0xea, 0x71, 0x42, 0x67, 0x24, 0xf2, 0x81, 0x41, 0x11, 0xd8,
            0x92, 0x3c
        }
    };

    TEST_COMMON_GOOD(TPM2B_IV, buffer,
        "b762d8cdea71426724f2814111d8923c",
        src);
}

void
test_TPM2B_IV_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_IV, buffer);
}

void
test_TPM2B_IV_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_IV, buffer);
}

void
test_TPM2B_MAX_BUFFER_good(void **state)
{
    UNUSED(state);

    static const TPM2B_MAX_BUFFER src = {
        .size = 16,
        .buffer = {
            0xae, 0xb6, 0x60, 0x23, 0x7f, 0x21, 0x15, 0x77, 0x4f, 0xcc, 0x56, 0x5a, 0x83, 0x10,
            0x38, 0x9a
        }
    };

    TEST_COMMON_GOOD(TPM2B_MAX_BUFFER, buffer,
        "aeb660237f2115774fcc565a8310389a",
        src);
}

void
test_TPM2B_MAX_BUFFER_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_MAX_BUFFER, buffer);
}

void
test_TPM2B_MAX_BUFFER_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_MAX_BUFFER, buffer);
}

void
test_TPM2B_MAX_NV_BUFFER_good(void **state)
{
    UNUSED(state);

    static const TPM2B_MAX_NV_BUFFER src = {
        .size = 16,
        .buffer = {
            0x68, 0x20, 0xf4, 0x34, 0xa0, 0x23, 0x4f, 0xbe, 0x54, 0xa8, 0x42, 0x19, 0x5c, 0x24,
            0x02, 0x83
        }
    };

    TEST_COMMON_GOOD(TPM2B_MAX_NV_BUFFER, buffer,
        "6820f434a0234fbe54a842195c240283",
        src);
}

void
test_TPM2B_MAX_NV_BUFFER_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_MAX_NV_BUFFER, buffer);
}

void
test_TPM2B_MAX_NV_BUFFER_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_MAX_NV_BUFFER, buffer);
}

void
test_TPM2B_NAME_good(void **state)
{
    UNUSED(state);

    static const TPM2B_NAME src = {
        .size = 16,
        .name = {
            0x77, 0x7c, 0xcd, 0xe5, 0x8d, 0xca, 0xe8, 0xf3, 0x32, 0x6a, 0xe9, 0xaf, 0x48, 0xa3,
            0x5c, 0xde
        }
    };

    TEST_COMMON_GOOD(TPM2B_NAME, name,
        "777ccde58dcae8f3326ae9af48a35cde",
        src);
}

void
test_TPM2B_NAME_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_NAME, name);
}

void
test_TPM2B_NAME_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_NAME, name);
}

void
test_TPM2B_NONCE_good(void **state)
{
    UNUSED(state);

    static const TPM2B_NONCE src = {
        .size = 16,
        .buffer = {
            0xe8, 0x86, 0xe3, 0x95, 0x91, 0xaf, 0x18, 0x44, 0x6a, 0x01, 0x2c, 0x06, 0x54, 0x8d,
            0x70, 0x86
        }
    };

    TEST_COMMON_GOOD(TPM2B_NONCE, buffer,
        "e886e39591af18446a012c06548d7086",
        src);
}

void
test_TPM2B_NONCE_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_NONCE, buffer);
}

void
test_TPM2B_NONCE_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_NONCE, buffer);
}

void
test_TPM2B_OPERAND_good(void **state)
{
    UNUSED(state);

    static const TPM2B_OPERAND src = {
        .size = 16,
        .buffer = {
            0x34, 0x38, 0x13, 0x8c, 0x1d, 0x6d, 0xd1, 0x30, 0x9c, 0x81, 0x55, 0x4e, 0xf5, 0x64,
            0x20, 0x2e
        }
    };

    TEST_COMMON_GOOD(TPM2B_OPERAND, buffer,
        "3438138c1d6dd1309c81554ef564202e",
        src);
}

void
test_TPM2B_OPERAND_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_OPERAND, buffer);
}

void
test_TPM2B_OPERAND_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_OPERAND, buffer);
}

void
test_TPM2B_PRIVATE_good(void **state)
{
    UNUSED(state);

    static const TPM2B_PRIVATE src = {
        .size = 16,
        .buffer = {
            0xa0, 0xb1, 0xaa, 0xea, 0xc1, 0xa3, 0x09, 0xc7, 0x52, 0xc5, 0xfa, 0xf2, 0xad, 0x2d,
            0x90, 0xa1
        }
    };

    TEST_COMMON_GOOD(TPM2B_PRIVATE, buffer,
        "a0b1aaeac1a309c752c5faf2ad2d90a1",
        src);
}

void
test_TPM2B_PRIVATE_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_PRIVATE, buffer);
}

void
test_TPM2B_PRIVATE_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_PRIVATE, buffer);
}

void
test_TPM2B_PRIVATE_KEY_RSA_good(void **state)
{
    UNUSED(state);

    static const TPM2B_PRIVATE_KEY_RSA src = {
        .size = 16,
        .buffer = {
            0x17, 0x4b, 0xbc, 0xa3, 0x79, 0x6c, 0x32, 0xe2, 0x35, 0x3c, 0x69, 0x78, 0xca, 0x53,
            0x02, 0x27
        }
    };

    TEST_COMMON_GOOD(TPM2B_PRIVATE_KEY_RSA, buffer,
        "174bbca3796c32e2353c6978ca530227",
        src);
}

void
test_TPM2B_PRIVATE_KEY_RSA_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_PRIVATE_KEY_RSA, buffer);
}

void
test_TPM2B_PRIVATE_KEY_RSA_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_PRIVATE_KEY_RSA, buffer);
}

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_good(void **state)
{
    UNUSED(state);

    static const TPM2B_PRIVATE_VENDOR_SPECIFIC src = {
        .size = 16,
        .buffer = {
            0xe3, 0x93, 0xb8, 0x6b, 0xdf, 0xd7, 0x69, 0x46, 0xa8, 0x9d, 0x3d, 0x37, 0xc1, 0x6b,
            0xec, 0x54
        }
    };

    TEST_COMMON_GOOD(TPM2B_PRIVATE_VENDOR_SPECIFIC, buffer,
        "e393b86bdfd76946a89d3d37c16bec54",
        src);
}

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_PRIVATE_VENDOR_SPECIFIC, buffer);
}

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_PRIVATE_VENDOR_SPECIFIC, buffer);
}

void
test_TPM2B_PUBLIC_KEY_RSA_good(void **state)
{
    UNUSED(state);

    static const TPM2B_PUBLIC_KEY_RSA src = {
        .size = 16,
        .buffer = {
            0x97, 0x39, 0xf9, 0x10, 0xe6, 0x50, 0xf0, 0xaa, 0x44, 0xb4, 0xb5, 0x48, 0x98, 0x93,
            0x4f, 0x94
        }
    };

    TEST_COMMON_GOOD(TPM2B_PUBLIC_KEY_RSA, buffer,
        "9739f910e650f0aa44b4b54898934f94",
        src);
}

void
test_TPM2B_PUBLIC_KEY_RSA_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_PUBLIC_KEY_RSA, buffer);
}

void
test_TPM2B_PUBLIC_KEY_RSA_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_PUBLIC_KEY_RSA, buffer);
}

void
test_TPM2B_SENSITIVE_DATA_good(void **state)
{
    UNUSED(state);

    static const TPM2B_SENSITIVE_DATA src = {
        .size = 16,
        .buffer = {
            0xa2, 0xae, 0x6e, 0xcd, 0x7a, 0xcc, 0xa6, 0xb5, 0x6f, 0x83, 0x34, 0xe9, 0x8f, 0xaf,
            0xbc, 0x1a
        }
    };

    TEST_COMMON_GOOD(TPM2B_SENSITIVE_DATA, buffer,
        "a2ae6ecd7acca6b56f8334e98fafbc1a",
        src);
}

void
test_TPM2B_SENSITIVE_DATA_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_SENSITIVE_DATA, buffer);
}

void
test_TPM2B_SENSITIVE_DATA_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_SENSITIVE_DATA, buffer);
}

void
test_TPM2B_SYM_KEY_good(void **state)
{
    UNUSED(state);

    static const TPM2B_SYM_KEY src = {
        .size = 16,
        .buffer = {
            0x1e, 0xea, 0x9a, 0x98, 0xb7, 0xf7, 0x3e, 0x5c, 0x6f, 0xc6, 0xf7, 0xa6, 0x23, 0xb6,
            0xd2, 0x97
        }
    };

    TEST_COMMON_GOOD(TPM2B_SYM_KEY, buffer,
        "1eea9a98b7f73e5c6fc6f7a623b6d297",
        src);
}

void
test_TPM2B_SYM_KEY_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_SYM_KEY, buffer);
}

void
test_TPM2B_SYM_KEY_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_SYM_KEY, buffer);
}

void
test_TPM2B_TEMPLATE_good(void **state)
{
    UNUSED(state);

    static const TPM2B_TEMPLATE src = {
        .size = 16,
        .buffer = {
            0xf3, 0x0e, 0x19, 0x74, 0x83, 0x9b, 0x95, 0x0c, 0x00, 0x3a, 0x7f, 0x58, 0x7a, 0xa7,
            0xb9, 0x3b
        }
    };

    TEST_COMMON_GOOD(TPM2B_TEMPLATE, buffer,
        "f30e1974839b950c003a7f587aa7b93b",
        src);
}

void
test_TPM2B_TEMPLATE_zero(void **state)
{
    UNUSED(state);

    TEST_COMMON_ZERO(TPM2B_TEMPLATE, buffer);
}

void
test_TPM2B_TEMPLATE_null(void **state)
{
    TEST_COMMON_NULL(TPM2B_TEMPLATE, buffer);
}
