/* SPDX-License-Identifier: BSD-2-Clause */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <stdlib.h>

#include <setjmp.h>
#include <cmocka.h>

#include "tss2_mu_yaml.h"

#define LOGMODULE tests
#include "util/log.h"
#include "util/aux_util.h"

/* AUTOGENERATED ASSISTED CODE using yaml_mu_gen.py. modify with care */

void
test_TPM2B_ATTEST_good(void **state);

void
test_TPM2B_ATTEST_zero(void **state);

void
test_TPM2B_ATTEST_null(void **state);

void
test_TPM2B_AUTH_good(void **state);

void
test_TPM2B_AUTH_zero(void **state);

void
test_TPM2B_AUTH_null(void **state);

void
test_TPM2B_CONTEXT_DATA_good(void **state);

void
test_TPM2B_CONTEXT_DATA_zero(void **state);

void
test_TPM2B_CONTEXT_DATA_null(void **state);

void
test_TPM2B_CONTEXT_SENSITIVE_good(void **state);

void
test_TPM2B_CONTEXT_SENSITIVE_zero(void **state);

void
test_TPM2B_CONTEXT_SENSITIVE_null(void **state);

void
test_TPM2B_DATA_good(void **state);

void
test_TPM2B_DATA_zero(void **state);

void
test_TPM2B_DATA_null(void **state);

void
test_TPM2B_DIGEST_good(void **state);

void
test_TPM2B_DIGEST_zero(void **state);

void
test_TPM2B_DIGEST_null(void **state);

void
test_TPM2B_ECC_PARAMETER_good(void **state);

void
test_TPM2B_ECC_PARAMETER_zero(void **state);

void
test_TPM2B_ECC_PARAMETER_null(void **state);

void
test_TPM2B_ENCRYPTED_SECRET_good(void **state);

void
test_TPM2B_ENCRYPTED_SECRET_zero(void **state);

void
test_TPM2B_ENCRYPTED_SECRET_null(void **state);

void
test_TPM2B_EVENT_good(void **state);

void
test_TPM2B_EVENT_zero(void **state);

void
test_TPM2B_EVENT_null(void **state);

void
test_TPM2B_ID_OBJECT_good(void **state);

void
test_TPM2B_ID_OBJECT_zero(void **state);

void
test_TPM2B_ID_OBJECT_null(void **state);

void
test_TPM2B_IV_good(void **state);

void
test_TPM2B_IV_zero(void **state);

void
test_TPM2B_IV_null(void **state);

void
test_TPM2B_MAX_BUFFER_good(void **state);

void
test_TPM2B_MAX_BUFFER_zero(void **state);

void
test_TPM2B_MAX_BUFFER_null(void **state);

void
test_TPM2B_MAX_NV_BUFFER_good(void **state);

void
test_TPM2B_MAX_NV_BUFFER_zero(void **state);

void
test_TPM2B_MAX_NV_BUFFER_null(void **state);

void
test_TPM2B_NAME_good(void **state);

void
test_TPM2B_NAME_zero(void **state);

void
test_TPM2B_NAME_null(void **state);

void
test_TPM2B_NONCE_good(void **state);

void
test_TPM2B_NONCE_zero(void **state);

void
test_TPM2B_NONCE_null(void **state);

void
test_TPM2B_OPERAND_good(void **state);

void
test_TPM2B_OPERAND_zero(void **state);

void
test_TPM2B_OPERAND_null(void **state);

void
test_TPM2B_PRIVATE_good(void **state);

void
test_TPM2B_PRIVATE_zero(void **state);

void
test_TPM2B_PRIVATE_null(void **state);

void
test_TPM2B_PRIVATE_KEY_RSA_good(void **state);

void
test_TPM2B_PRIVATE_KEY_RSA_zero(void **state);

void
test_TPM2B_PRIVATE_KEY_RSA_null(void **state);

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_good(void **state);

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_zero(void **state);

void
test_TPM2B_PRIVATE_VENDOR_SPECIFIC_null(void **state);

void
test_TPM2B_PUBLIC_KEY_RSA_good(void **state);

void
test_TPM2B_PUBLIC_KEY_RSA_zero(void **state);

void
test_TPM2B_PUBLIC_KEY_RSA_null(void **state);

void
test_TPM2B_SENSITIVE_DATA_good(void **state);

void
test_TPM2B_SENSITIVE_DATA_zero(void **state);

void
test_TPM2B_SENSITIVE_DATA_null(void **state);

void
test_TPM2B_SYM_KEY_good(void **state);

void
test_TPM2B_SYM_KEY_zero(void **state);

void
test_TPM2B_SYM_KEY_null(void **state);

void
test_TPM2B_TEMPLATE_good(void **state);

void
test_TPM2B_TEMPLATE_zero(void **state);

void
test_TPM2B_TEMPLATE_null(void **state);

///* AUTOGENERATED ASSISTED CODE using yaml_mu_gen.py tpms_simple_test_protos. modify with care */
//
//void
//test_TPMS_AC_OUTPUT_good(void **state);
//
//void
//test_TPMS_AC_OUTPUT_zero(void **state);
//
//void
//test_TPMS_AC_OUTPUT_null(void **state);
//
void
test_TPMS_ALG_PROPERTY_good(void **state);

void
test_TPMS_ALG_PROPERTY_zero(void **state);

void
test_TPMS_ALG_PROPERTY_null(void **state);
//
//void
//test_TPMS_CLOCK_INFO_good(void **state);
//
//void
//test_TPMS_CLOCK_INFO_zero(void **state);
//
//void
//test_TPMS_CLOCK_INFO_null(void **state);
//
//void
//test_TPMS_NV_PIN_COUNTER_PARAMETERS_good(void **state);
//
//void
//test_TPMS_NV_PIN_COUNTER_PARAMETERS_zero(void **state);
//
//void
//test_TPMS_NV_PIN_COUNTER_PARAMETERS_null(void **state);
//
//void
//test_TPMS_SCHEME_ECDAA_good(void **state);
//
//void
//test_TPMS_SCHEME_ECDAA_zero(void **state);
//
//void
//test_TPMS_SCHEME_ECDAA_null(void **state);
//
//void
//test_TPMS_SCHEME_HASH_good(void **state);
//
//void
//test_TPMS_SCHEME_HASH_zero(void **state);
//
//void
//test_TPMS_SCHEME_HASH_null(void **state);
//
//void
//test_TPMS_SCHEME_XOR_good(void **state);
//
//void
//test_TPMS_SCHEME_XOR_zero(void **state);
//
//void
//test_TPMS_SCHEME_XOR_null(void **state);
//
//void
//test_TPMS_TAGGED_PROPERTY_good(void **state);
//
//void
//test_TPMS_TAGGED_PROPERTY_zero(void **state);
//
//void
//test_TPMS_TAGGED_PROPERTY_null(void **state);
//

void test_TPMS_ATTEST_bill(void **state) {
    (void)state;

    TPMS_ATTEST x;
    x.clockInfo.clock = 0xbadcc0de;
    x.clockInfo.resetCount = 42;
    x.clockInfo.restartCount = 69;
    x.clockInfo.safe = 0;

    x.extraData.size = 2;
    x.extraData.buffer[0] = 0xFF;
    x.extraData.buffer[1] = 0xAA;

    x.firmwareVersion = 0xDEADBEEF;

    x.magic = 0xbadcafe;

    x.qualifiedSigner.size = 32;
    memset(x.qualifiedSigner.name, 0xBB, 32);

    x.type = TPM2_ST_ATTEST_CREATION;
    x.attested.creation.creationHash.size = 32;
    memset(x.attested.creation.creationHash.buffer, 32, 32);
    x.attested.creation.objectName.size = 34;
    memset(x.attested.creation.objectName.name, 34, 34);

    char *yaml = NULL;
    TSS2_RC rc = Tss2_MU_YAML_TPMS_ATTEST_Marshal(&x, &yaml);
    assert_int_equal(rc, TSS2_RC_SUCCESS);
}

int
main(int argc, char *argv[])
{
    const struct CMUnitTest tests[] = {
            /* AUTOGENERATED ASSISTED CODE using yaml_mu_gen.py all_test_list. modify with care */
            cmocka_unit_test(test_TPM2B_ATTEST_good),
            cmocka_unit_test(test_TPM2B_ATTEST_zero),
            cmocka_unit_test(test_TPM2B_ATTEST_null),
            cmocka_unit_test(test_TPM2B_AUTH_good),
            cmocka_unit_test(test_TPM2B_AUTH_zero),
            cmocka_unit_test(test_TPM2B_AUTH_null),
            cmocka_unit_test(test_TPM2B_CONTEXT_DATA_good),
            cmocka_unit_test(test_TPM2B_CONTEXT_DATA_zero),
            cmocka_unit_test(test_TPM2B_CONTEXT_DATA_null),
            cmocka_unit_test(test_TPM2B_CONTEXT_SENSITIVE_good),
            cmocka_unit_test(test_TPM2B_CONTEXT_SENSITIVE_zero),
            cmocka_unit_test(test_TPM2B_CONTEXT_SENSITIVE_null),
            cmocka_unit_test(test_TPM2B_DATA_good),
            cmocka_unit_test(test_TPM2B_DATA_zero),
            cmocka_unit_test(test_TPM2B_DATA_null),
            cmocka_unit_test(test_TPM2B_DIGEST_good),
            cmocka_unit_test(test_TPM2B_DIGEST_zero),
            cmocka_unit_test(test_TPM2B_DIGEST_null),
            cmocka_unit_test(test_TPM2B_ECC_PARAMETER_good),
            cmocka_unit_test(test_TPM2B_ECC_PARAMETER_zero),
            cmocka_unit_test(test_TPM2B_ECC_PARAMETER_null),
            cmocka_unit_test(test_TPM2B_ENCRYPTED_SECRET_good),
            cmocka_unit_test(test_TPM2B_ENCRYPTED_SECRET_zero),
            cmocka_unit_test(test_TPM2B_ENCRYPTED_SECRET_null),
            cmocka_unit_test(test_TPM2B_EVENT_good),
            cmocka_unit_test(test_TPM2B_EVENT_zero),
            cmocka_unit_test(test_TPM2B_EVENT_null),
            cmocka_unit_test(test_TPM2B_ID_OBJECT_good),
            cmocka_unit_test(test_TPM2B_ID_OBJECT_zero),
            cmocka_unit_test(test_TPM2B_ID_OBJECT_null),
            cmocka_unit_test(test_TPM2B_IV_good),
            cmocka_unit_test(test_TPM2B_IV_zero),
            cmocka_unit_test(test_TPM2B_IV_null),
            cmocka_unit_test(test_TPM2B_MAX_BUFFER_good),
            cmocka_unit_test(test_TPM2B_MAX_BUFFER_zero),
            cmocka_unit_test(test_TPM2B_MAX_BUFFER_null),
            cmocka_unit_test(test_TPM2B_MAX_NV_BUFFER_good),
            cmocka_unit_test(test_TPM2B_MAX_NV_BUFFER_zero),
            cmocka_unit_test(test_TPM2B_MAX_NV_BUFFER_null),
            cmocka_unit_test(test_TPM2B_NAME_good),
            cmocka_unit_test(test_TPM2B_NAME_zero),
            cmocka_unit_test(test_TPM2B_NAME_null),
            cmocka_unit_test(test_TPM2B_NONCE_good),
            cmocka_unit_test(test_TPM2B_NONCE_zero),
            cmocka_unit_test(test_TPM2B_NONCE_null),
            cmocka_unit_test(test_TPM2B_OPERAND_good),
            cmocka_unit_test(test_TPM2B_OPERAND_zero),
            cmocka_unit_test(test_TPM2B_OPERAND_null),
            cmocka_unit_test(test_TPM2B_PRIVATE_good),
            cmocka_unit_test(test_TPM2B_PRIVATE_zero),
            cmocka_unit_test(test_TPM2B_PRIVATE_null),
            cmocka_unit_test(test_TPM2B_PRIVATE_KEY_RSA_good),
            cmocka_unit_test(test_TPM2B_PRIVATE_KEY_RSA_zero),
            cmocka_unit_test(test_TPM2B_PRIVATE_KEY_RSA_null),
            cmocka_unit_test(test_TPM2B_PRIVATE_VENDOR_SPECIFIC_good),
            cmocka_unit_test(test_TPM2B_PRIVATE_VENDOR_SPECIFIC_zero),
            cmocka_unit_test(test_TPM2B_PRIVATE_VENDOR_SPECIFIC_null),
            cmocka_unit_test(test_TPM2B_PUBLIC_KEY_RSA_good),
            cmocka_unit_test(test_TPM2B_PUBLIC_KEY_RSA_zero),
            cmocka_unit_test(test_TPM2B_PUBLIC_KEY_RSA_null),
            cmocka_unit_test(test_TPM2B_SENSITIVE_DATA_good),
            cmocka_unit_test(test_TPM2B_SENSITIVE_DATA_zero),
            cmocka_unit_test(test_TPM2B_SENSITIVE_DATA_null),
            cmocka_unit_test(test_TPM2B_SYM_KEY_good),
            cmocka_unit_test(test_TPM2B_SYM_KEY_zero),
            cmocka_unit_test(test_TPM2B_SYM_KEY_null),
            cmocka_unit_test(test_TPM2B_TEMPLATE_good),
            cmocka_unit_test(test_TPM2B_TEMPLATE_zero),
            cmocka_unit_test(test_TPM2B_TEMPLATE_null),
//            cmocka_unit_test(test_TPMS_AC_OUTPUT_good),
//            cmocka_unit_test(test_TPMS_AC_OUTPUT_zero),
//            cmocka_unit_test(test_TPMS_AC_OUTPUT_null),
            cmocka_unit_test(test_TPMS_ALG_PROPERTY_good),
            cmocka_unit_test(test_TPMS_ALG_PROPERTY_zero),
            cmocka_unit_test(test_TPMS_ALG_PROPERTY_null),
            cmocka_unit_test(test_TPMS_ATTEST_bill),
//            cmocka_unit_test(test_TPMS_CLOCK_INFO_good),
//            cmocka_unit_test(test_TPMS_CLOCK_INFO_zero),
//            cmocka_unit_test(test_TPMS_CLOCK_INFO_null),
//            cmocka_unit_test(test_TPMS_NV_PIN_COUNTER_PARAMETERS_good),
//            cmocka_unit_test(test_TPMS_NV_PIN_COUNTER_PARAMETERS_zero),
//            cmocka_unit_test(test_TPMS_NV_PIN_COUNTER_PARAMETERS_null),
//            cmocka_unit_test(test_TPMS_SCHEME_ECDAA_good),
//            cmocka_unit_test(test_TPMS_SCHEME_ECDAA_zero),
//            cmocka_unit_test(test_TPMS_SCHEME_ECDAA_null),
//            cmocka_unit_test(test_TPMS_SCHEME_HASH_good),
//            cmocka_unit_test(test_TPMS_SCHEME_HASH_zero),
//            cmocka_unit_test(test_TPMS_SCHEME_HASH_null),
//            cmocka_unit_test(test_TPMS_SCHEME_XOR_good),
//            cmocka_unit_test(test_TPMS_SCHEME_XOR_zero),
//            cmocka_unit_test(test_TPMS_SCHEME_XOR_null),
//            cmocka_unit_test(test_TPMS_TAGGED_PROPERTY_good),
//            cmocka_unit_test(test_TPMS_TAGGED_PROPERTY_zero),
//            cmocka_unit_test(test_TPMS_TAGGED_PROPERTY_null),

    };
    return cmocka_run_group_tests(tests, NULL, NULL);
}
